### ISSUE TITLE
Search result screen sometimes broken

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/ios#100]
Various reports of the search result screen being broken - search for something and it gets in a stuck state with a 'No results' graphic shown but no possibility of cancellation, and the keyboard shown sometimes, sometimes not.

I get this sometimes (but not always) on my own copy.

![image](https://cloud.githubusercontent.com/assets/361423/16146076/15c59176-3474-11e6-9bdb-d76a2a12de77.png)

**Comment by mvl22** [comment]
User report:
https://twitter.com/psyklyn/status/743377408296882176

**Comment by neilkachu** [comment]
OK, will take a look, have there been any API changes to this call?

**Comment by mvl22** [comment]
No.

**Comment by neilkachu** [comment]
Ok, reproduced, the error is correct but the view size it is displayed at is incorrect. deleting some characters will recover it FYI.

**Comment by neilkachu** [comment]
b412 fixes this issue, it's on TF now to test. You could reply to the twitter user about the deletion key as this resolves this temporarily.
