### ISSUE TITLE
no file:docs/APIKey_live.txt

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [cyclestreets/ios#102]
I downloaded and compiled this on my XCode. There is not docs/APIKey_live.txt;

**Comment by neilkachu** [comment]
The project only requires this for release builds so the reference (it'll be in red in the file listing) can be deleted.

**Comment by mvl22** [comment]
Neil, can we add a README in the same directory explaining this?

If it could make clear that people can get an API key at:
https://www.cyclestreets.net/api/apply/
that would be good too.

**Comment by neilkachu** [comment]
Can do.
