### ISSUE TITLE
Map text/size unreadable

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/ios#81]
Several reports that, in the new 3.0 release, the text size is too small to read.

**Comment by mvl22** [comment]
Just to say that thanks to @gravitystorm, the Android app is now seeing real retina tiles (at 2x) for the OpenCycleMap layer, as of
https://github.com/cyclestreets/tilecache/commit/6469ae1bebe04f48bba567d34d9a955321d16f9d

@neilkachu I'm still very keen to get this working as the app shows tiles painfully small - I think your Dec 4, 2014 posting suggested something might be possible.

**Comment by neilkachu** [comment]
I'll have another look at this, looks like you're just upscaling the 256 px tiles to the upscaled size when caching and drawing into a larger tile size. As we know have x3 devices this end too we'll need to handle this more generically too. But I'm not sure this is entirely the correct approach, the actual map styling needs to be different server side too, the MapBox post shows why.

**Comment by neilkachu** [comment]
I'll have another look at this, the SO issue was just a method name, not a removal or anything like that. so the MBXRasterTileRenderer.m not MBXRasterTileOverlay.m might just work, they are setting the tileSize to 512 and downloading x2 512px tiles but it's the overriding of how to draw these into the graphics layer that is key. I'll cover this into CS logic and get back to you.

**Comment by mvl22** [comment]
The ideal is definitely that you request from the server either standard 1x tiles (and the server returns 256x256) or request ....x2.png tiles and get back 512x512. (And in future x3 as screens become higher resolution, etc.). If possible avoid the option of upscaling on the device.

This means the tileserver at our end can then work out whether it is supposed to upscale or whether to pass on real Retina tiles - more and more providers now are providing proper x2 tiles, with the actual cartography modified to have more appropriate label sizes, etc.

**Comment by neilkachu** [comment]
Well that appears to-just-work!
![simulator screen shot 5 jan 2016 11 31 15](https://cloud.githubusercontent.com/assets/476062/12114209/e1d9100e-b39f-11e5-91cd-ef3a5c15e75d.png)

**Comment by mvl22** [comment]
Wow, that is so much better.

Are other tilesets like Vector still fine, and does the OSM style (which we are upscaling) also appear the same way (albeit more pixelated because the server is upscaling)?

**Comment by neilkachu** [comment]
OSM looks like it works fine too, others look ok too. Currently all raster tile sources are passing through this renderer even if they are not retina enabled this side, I'll do some tests with this on/off but as its looking up the tileSize for the source before re-rendering it should be fine as a global replacement for raster tile sets. The Apple vector tiles don't use this system at all so aren't affected, they do the correct thing anyway.

**Comment by mvl22** [comment]
Great; that sounds perfect. Definitely best if the server can do all the decision-making. Let's get this into a release soon-as (preferably with all the other new stuff - will contact you on e-mail re that).

What scaling factors need to be supported? Currently we have 1, 1.5, 2, 3 enabled. Do you need any more? Are you able to look this up automatically from the device, rather than hard-code it to 2?

**Comment by neilkachu** [comment]
The retina scale is derived from the device's screen scale, iOS only supports 1,2 & 3 no odd half sizes.  But as the app is not enabled for x3 devices natively this shouldnt be an issue at the mo (it requires the entire app converting over to Auto layout).   Is there a way to ask the tile source server what scales it supports? currently we have the switch this on this end so requires a build.    

OSM looks ok on device if a bit pixely, you can be the judge.

**Comment by mvl22** [comment]
> Is there a way to ask the tile source server what scales it supports?

No. We don't plan to add an API for this. Most tile providers are the same: they publish a list of what they support, and apps just add support for those levels, so:

> currently we have the switch this on this end so requires a build.

yes, that's therefore fine.

> OSM looks ok on device if a bit pixely, you can be the judge.

Yes, it will do a bit. I'll have a look when a build comes through on Testflight. I think it is likely to be better than the unreadability problem though!

**Comment by neilkachu** [comment]
OK, leave it with me, so for now only OCM & OSM will have this enabled.

**Comment by mvl22** [comment]
> only OCM & OSM will have this enabled.

Plus CNS and Ordnance Survey - any reason not to add those? They are all coming from the same tileserver so have the 2x upscaling support.

**Comment by neilkachu** [comment]
OK, I'll switch all these on too then!
Build on it's way with some other fixes too.

**Comment by mvl22** [comment]
> OK, I'll switch all these on too then!

Thanks. Please work on the principle that if a source is coming from the CycleStreets tileserver, then support should be present for 1x, 2x, etc.

**Comment by mvl22** [comment]
Now in latest release - thanks for all the comments and work on this.

We'll have to wait for the Mapnik layer and OS layers to be improved upstream, but the app for now has the code in place.

**Comment by mvl22** [comment]
Mapnik (OSM) style issue:
https://github.com/gravitystorm/openstreetmap-carto/issues/2038
