### ISSUE TITLE
App not saving recent routes

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/ios#86]
We've had a bug report as follows:

> Since January the app does not save my recent routes. This makes it much less useful.

I can reproduce this in the beta:

- Plan route
- It is not shown in the Routes page.

I notice I do have a route saved on 3rd May.

**Comment by neilkachu** [comment]
Hmm, not sure, there has been no January change. I'll be doing some 3.0.1 bug fixes this week for a 3.0.2 release soon so I'll add this to the list.

**Comment by neilkachu** [comment]
Can you take a look in Settings/Usage/ManageStorage for the available space and what CS is using in the list? There are no year checks in the code.

**Comment by mvl22** [comment]
Mine says 94.1MB.
