### ISSUE TITLE
Move tileserver to HTTPS

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/ios#98]
We're gradually moving all our infrastructure to HTTPS.

The tileserver is available as an HTTPS endpoint now.

All these need to be moved:
https://github.com/cyclestreets/ios/search?utf8=%E2%9C%93&q=http%3A%2F%2Ftile.cyclestreets.net

**Comment by mvl22** [comment]
Sub-subdomains, i.e.

{a,b,c}.tile.cyclestreets.net

is now available under HTTPS.

**Comment by mvl22** [comment]
The latter point is noted as separate issue #104.

**Comment by neilkachu** [comment]
Complete for next build
